In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df['Spam']=df['Category'].apply(lambda x : 1 if x =='spam' else 0 )
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

> ### **Train Test Split**

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Spam,test_size=0.2)

In [5]:
X_train.shape

(4457,)

In [6]:
X_train[:4]

2725                                  Nope... C ü then...
397     Was actually sleeping and still might when u c...
4290                   Okay, good, no problem, and thanx!
3153    Hard LIVE 121 chat just 60p/min. Choose your g...
Name: Message, dtype: object

> ### **Process data with count vectorizer**

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_train_cv

<4457x7757 sparse matrix of type '<class 'numpy.int64'>'
	with 59878 stored elements in Compressed Sparse Row format>

In [8]:
X_train_np=X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
np.where(X_train_np[0]!=0)

(array([4866, 6853], dtype=int64),)

In [10]:
dir(cv)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [11]:
cv.vocabulary_

{'nope': 4866,
 'then': 6853,
 'was': 7412,
 'actually': 812,
 'sleeping': 6248,
 'and': 967,
 'still': 6504,
 'might': 4526,
 'when': 7494,
 'call': 1623,
 'back': 1211,
 'so': 6307,
 'text': 6813,
 'is': 3813,
 'gr8': 3272,
 'you': 7722,
 'rock': 5850,
 'sis': 6216,
 'will': 7531,
 'send': 6046,
 'wen': 7472,
 'wake': 7381,
 'okay': 4974,
 'good': 3241,
 'no': 4845,
 'problem': 5475,
 'thanx': 6833,
 'hard': 3396,
 'live': 4216,
 '121': 282,
 'chat': 1765,
 'just': 3940,
 '60p': 576,
 'min': 4534,
 'choose': 1826,
 'your': 7728,
 'girl': 3196,
 'connect': 1990,
 '09094646899': 242,
 'now': 4893,
 'cheap': 1770,
 'uk': 7153,
 'biggest': 1361,
 'service': 6067,
 'vu': 7356,
 'bcm1896wc1n3xx': 1280,
 'well': 7469,
 'am': 941,
 'officially': 4960,
 'in': 3705,
 'philosophical': 5231,
 'hole': 3530,
 'if': 3663,
 'wanna': 7398,
 'at': 1127,
 'home': 3536,
 'ready': 5645,
 'to': 6963,
 'be': 1288,
 'saved': 5959,
 'please': 5297,
 'ask': 1104,
 'mummy': 4694,
 'father': 2836,
 'liked': 417

In [12]:
cv.get_feature_names_out()[7721]

'yorge'

In [13]:
X_train_np[0][7721]

0

> ### **Train the naive bayes model**

In [14]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [15]:
X_test_cv=cv.transform(X_test)
X_test_np=X_test_cv.toarray()
X_test_cv.shape

(1115, 7757)

In [16]:
y_predicted=model.predict(X_test_cv)
y_predicted


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = cv.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

> ### **Classification Report**

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       976
           1       0.98      0.89      0.93       139

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

